language: python
os: linux

install:
  - rm --force ./dist/*
  - python setup.py sdist bdist_wheel
  - echo installing ./dist/sdepy*.whl
  - pip install --no-deps --ignore-installed ./dist/sdepy*.whl

# fast tests with dependencies >= minimal requirements
# for all supported python versions
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install numpy>=1.15.2 scipy>=0.19.1 pytest>=3.8.1

script:
  - python runtests.py 'setup_tests()'
  - pushd ./build/tests
  - python runtests.py 'no_source()' 'run_fast()'
  - popd
  - python runtests.py 'exit_tests()'

# additional tests
jobs:
  include:
    # fast tests with minimal requirements for python and dependencies
    - python: 3.5
      before_install:
        - pip install numpy==1.15.2 scipy==0.19.1 pytest==3.8.1

    # full python 3.7 tests with specified dependencies
    - python: 3.7
      before_install:
        - pip install numpy==1.18.3 scipy==1.4.1 pytest==5.4.1
        # needs matplotlib for quickguide doctests
        - pip install matplotlib>=3.1
      script:
        - python runtests.py 'setup_tests()'
        - pushd ./build/tests
        - python runtests.py 'no_source()' 'run_full()'
        - python runtests.py 'run_quickguide()'
        - popd
        - python runtests.py 'exit_tests()'

    # full python 3.8 tests with specified dependencies
    - python: 3.8
      before_install:
        - pip install numpy==1.18.3 scipy==1.4.1 pytest==5.4.1
        # needs matplotlib for quickguide doctests
        - pip install matplotlib>=3.1
      script:
        - python runtests.py 'setup_tests()'
        - pushd ./build/tests
        - python runtests.py 'no_source()' 'run_full()'
        - python runtests.py 'run_quickguide()'
        - popd
        - python runtests.py 'exit_tests()'
