language: python
sudo: false

install:
  - rm --force ./dist/*
  - python setup.py sdist bdist_wheel
  - echo installing ./dist/sdepy*.whl
  - pip install --no-deps --ignore-installed ./dist/sdepy*.whl

matrix:
  # minimum requirements, fast tests
  - python: 3.5
  - python: 3.6
  - python: 3.7
  - python: 3.8

  before_install:
    - pip install numpy>=1.15.2 scipy>=0.19.1 pytest>=3.8.1

  script:
    - python runtests.py 'setup_tests()'
    - pushd ./build/tests
    - python runtests.py 'no_source()' 'run_fast()'
    - popd
    - python runtests.py 'exit_tests()'
