language: python
sudo: false

install:
  - rm --force ./dist/*
  - python setup.py sdist bdist_wheel
  - echo installing ./dist/sdepy*.whl
  - pip install --no-deps --ignore-installed ./dist/sdepy*.whl

matrix:
  include:
    # minimum requirements, fast tests
    - python: 3.5
      before_install:
        - pip install numpy==1.11.3 scipy==0.18.1 nose==1.3.7
      script:
        - python runtests.py 'setup_tests()'
        - pushd ./build/tests
        - python runtests.py 'no_source()' 'run_fast()'
        - popd
        - python runtests.py 'exit_tests()'
    # python 3.6, latest versions of other dependencies, fast tests
    - python: 3.6
      before_install:
        - pip install numpy>=1.16 scipy>=1.2 nose>=1.3.7
      script:
        - python runtests.py 'setup_tests()'
        - pushd ./build/tests
        - python runtests.py 'no_source()' 'run_fast()'
        - popd
        - python runtests.py 'exit_tests()'
    # python 3.7, latest versions of other dependencies, full tests
    # with code coverage
    - python: 3.7
      dist: xenial  # see travis-ci/travis-ci/issues/9815
      sudo: true
      before_install:
        - pip install numpy>=1.16 scipy>=1.2 nose>=1.3.7
        # - pip install matplotlib>=2.1.0  # needed for quickguide doctests
        - pip install coverage>=4.5.1 codecov>=2.0.15
      script:
        - python runtests.py 'setup_tests()'
        - pushd ./build/tests
        - coverage run --rcfile=../../.coveragerc runtests.py 'no_source()' 'run_full()'
        - popd
        - python runtests.py 'exit_tests()'
      after_success:
        - codecov

